# Generated by Django 3.0.3 on 2020-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitnumber',
            name='level',
            field=models.IntegerField(max_length=2),
        ),
    ]
