# Generated by Django 3.0.3 on 2020-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionForm', '0002_auto_20200309_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
