# Generated by Django 3.0.3 on 2020-03-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionForm', '0004_auto_20200309_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectionForm.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(max_length=100),
        ),
    ]
