# Generated by Django 3.0.3 on 2020-03-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionForm', '0006_auto_20200309_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitnumber',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='unitnumber',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='unitnumber',
            name='phase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectionForm.Phase', verbose_name='Phase'),
        ),
    ]
