# Generated by Django 3.0.3 on 2020-03-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company_id',
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(choices=[('Johor', 'Johor'), ('Kuala Lumpur', 'Kuala Lumpur'), ('Penang', 'Penang')], default=None, max_length=55),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
