# Generated by Django 3.0.4 on 2020-03-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20200317_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(blank=True, default=True, max_length=55),
        ),
    ]
