# Generated by Django 3.0.4 on 2020-04-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20200330_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitnumber',
            name='max_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unitnumber',
            name='max_unit_per_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(max_length=100, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_short_form',
            field=models.CharField(max_length=10, verbose_name='Project Short Name'),
        ),
        migrations.AlterField(
            model_name='unitnumber',
            name='unit_number',
            field=models.IntegerField(),
        ),
    ]
