# Generated by Django 3.0.4 on 2020-04-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection02',
            name='inspection_count',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
