# Generated by Django 3.0.4 on 2020-04-10 15:15

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection01',
            name='inspection_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='accept',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='accept_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='consultant',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='consultant_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='consultant_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='consultant_reinspection',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='contractor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='contractor_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='contractor_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='inspection',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inspection02',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
