# Generated by Django 3.0.4 on 2020-03-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection01',
            name='rev',
        ),
    ]
