# Generated by Django 3.0.4 on 2020-04-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedetail',
            name='legend',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='templatedetail',
            name='question_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
