# Generated by Django 3.0.4 on 2020-03-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='numberseries',
            name='current',
            field=models.IntegerField(default=1),
        ),
    ]
