# Generated by Django 3.0.4 on 2020-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_inspection02_inspection_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection01',
            name='inspection_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
